language: java

addons:
  sonarcloud:
    organization: "nareshkumar-h-github"
    #token:
     # secure: 584e849e517e4e59720f42f40a80206739f92078
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'   
    
#jobs:
#  include:
    #- stage: pre-build
     # script: mvn clean
  
    #- stage: test
    #  script: mvn test org.jacoco:jacoco-maven-plugin:prepare-agent
    
    #- stage: build
     # script: mvn install
      
    #- stage: quality
     # script: mvn sonar:sonar

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  slack: javafullstackgroup:cU6yGmSyVRshhITnnXELpBug
